# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: TEST
  displayName: TESTING-STAGES
  jobs:
  - job: TESTJOB
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
- stage: BuildDockerImage
  displayName: Building-image
  jobs:
  - job: Buildjob
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'MYNEWDOCKER'
        command: 'build'
        Dockerfile: '**/Dockerfile'